services:
  - type: web
    name: toy-shop
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn toy_shop.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: REDIS_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
    disk:
      name: sqlite
      mountPath: /opt/render/project/src/
      sizeGB: 1
    autoDeploy: true 