# Generated by Django 5.1.6 on 2025-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_order_alter_review_rating_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название бренда'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название бренда'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='toy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='toy',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='toy',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='toy',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='toy',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='toy',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
