# Generated by Django 5.1.6 on 2025-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_agegroup_description_en_agegroup_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='age_groups/', verbose_name='Изображение'),
        ),
    ]
